
#General mod settings
[general]
	#No comment
	#Range: > -2147483648
	calmTimePerUse = 72000
	#No comment
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	healPerUse = 7.0
	#No comment
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	healPerHit = 3.0
	#No comment
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	healPerKill = 10.0
	#No comment
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	heal1HealthPerXTicks = 6000.0
	#No comment
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	calmItemSearchRange = 12.0
	#No comment
	#Range: > -2147483648
	chestSearchRange = 20
	#They already search more relaxed like if they dont need food, but this will fully lock them out unless they need it
	onlySeekFoodIfNeeded = false
	#No comment
	#Range: > -2147483648
	tickDelayBetweenPlaying = 72000

